india_data = {
    "Andaman and Nicobar Islands": {
        "Nicobar": ["Car Nicobar", "Great Nicobar", "Little Nicobar"],
        "North and Middle Andaman": ["Diglipur", "Mayabunder", "Rangat"],
        "South Andaman": ["Port Blair"]
    },
    "Andhra Pradesh": {
        "Anantapur": ["Anantapur", "Dharmavaram", "Guntakal", "Hindupur", "Kadiri", "Kalyandurg", "Nallamada", "Puttaparthi", "Rayadurg", "Singanamala"],
        "Chittoor": ["Chittoor", "Gangadhara Nellore", "Kuppam", "Madanapalle", "Nagari", "Palamaner", "Pileru", "Punganur", "Srikalahasti", "Tirupati"],
        "East Godavari": ["Amalapuram", "Anaparti", "Bhimavaram", "Kakinada", "Mummidivaram", "Peddapuram", "Rajahmundry", "Sakhinetipalli", "Tuni"],
        "Guntur": ["Amaravathi", "Bapatla", "Chilakaluripet", "Guntur", "Macherla", "Narasaraopet", "Nizampatnam", "Ponnur", "Prathipadu", "Tenali"],
        "Krishna": ["Gudivada", "Jaggayyapeta", "Machilipatnam", "Mopidevi", "Nuzvid", "Penamaluru", "Vijayawada", "Vuyyuru"],
        "Kurnool": ["Adoni", "Allagadda", "Gadwal", "Kurnool", "Nandyal", "Orvakal", "Panyam", "Yemmiganur"],
        "Prakasam": ["Chirala", "Chinaganjam", "Cumbum", "Darsi", "Giddalur", "Kanigiri", "Kandukur", "Markapuram", "Ongole", "Podili"],
        "Srikakulam": ["Amadalavalasa", "Etcherla", "Hiramandalam", "Kalingapatnam", "Narasingapuram", "Palasa", "Pathapatnam", "Rajam", "Srikakulam", "Tekkali"],
        "Visakhapatnam": ["Anakapalle", "Bheemunipatnam", "Chodavaram", "Gajuwaka", "Narsipatnam", "Pendurthi", "Pithapuram", "Visakhapatnam"],
        "Vizianagaram": ["Bobbili", "Cheepurupalli", "Gajapathinagaram", "Garividi", "Kothavalasa", "Parvathipuram", "Salur", "Vizianagaram"],
        "West Godavari": ["Bhimavaram", "Denduluru", "Eluru", "Jangareddygudem", "Narasapuram", "Palakollu", "Tadepalligudem", "Tanuku"]
    },

    "Arunachal Pradesh": {
        "Anjaw": [
            "Chaglagam Circle",
            "Goiliang Circle",
            "Hawai Hq",
            "Hayuliang Adc",
            "Kibithoo Circle",
            "Manchal Circle",
            "Metengliang Circle",
            "Walong Circle"
        ],
        "Bichom": ["Dambuk", "Siyum", "Sangram"],
        "Changlang": [
            "Bordumsa Adc",
            "Changlang Hq",
            "Diyun Eac",
            "Jairampur Adc",
            "Kantang Circle",
            "Kharsang Circle",
            "Khimiyang Eac",
            "Lyngok Longtoi Circle",
            "Manmao Eac",
            "Miao Adc",
            "Nampong Sdo",
            "Namtok Eac",
            "Renuk Circle",
            "Tikhak Rima Putok Circle",
            "Vijoynagar Eac",
            "Yatdam Circle"
        ],
        "Dibang Valley": [
            "Anelih",
            "Anini",
            "Dambuen Circle",
            "Etalin",
            "Kronli (Arzoo Circle)",
            "Mipi"
        ],
        "East Kameng": [
            "Bhalukpong",
            "Bomdila",
            "Dirang",
            "Kalaktang",
            "Kamakshya Hills",
            "Nafra",
            "Pipu",
            "Sawa Circle",
            "Taliha",   
            "Tato",
            "Thrizino",
            "Yingkiong"
        ],  
        "East Siang": [
            "Alinyo Circle",
            "Boleng Circle",
            "Dambuk Circle",
            "Kaying Circle",
            "Mebo Circle",
            "Pasighat Hq",
            "Ruksin Circle",
            "Sile-Oyan Circle",
            "Yomcha Circle"
        ],
        "Kamle": [
            "Raga Circle",
            "Pipu Circle",
            "Ziro Circle"
        ],
        "Kra Daadi": [
            "Dumsi Circle",
            "Pipsorang Circle",
            "Palin Circle"
        ],
        "Kurung Kumey": [
            "Bagra Circle",
            "Damin Circle",
            "Koloriang Circle",
            "Nyapin Circle",
            "Sarli Circle",
            "Tali Circle"
        ],
        "Lepa Rada": [
            "Basar Circle",
            "Koksa Circle",
            "Sago Circle"
        ],
        "Lohit": [
            "Chambang Circle",
            "Dibang Valley",
            "Hayuliang Circle",
            "Hawai Circle",
            "Lohit Circle",
            "Lohit Hq",
            "Meka Circle",
            "Namsai Circle",
            "Narottam Nagar Circle",
            "Sunpura Circle"
        ],
        "Longding": [
            "Longding Circle",
            "Namsang Circle",
            "Pumao Circle"
        ],
        "Lower Dibang Valley": [
            "Anelih Circle",
            "Dambuk Circle",
            "Meka Circle",
            "Roing Hq",
            "Sadiya Circle",
            "Sunpura Circle"
        ],
        "Lower Siang": [
            "Likabali Circle",      
            "Mebo Circle",
            "Morang Circle",
            "Pangin Circle",
            "Siyum Circle"
        ],
        "Lower Subansiri": [    
            "Bamin Michi Circle",
            "Daporijo Hq",
            "Dumporijo Circle",
            "Gensi Circle",
            "Kali Circle",
            "Kaying Circle",
            "Limeking Circle",
            "Mebo Circle",
            "Nacho Circle",
            "Pissa Circle"
        ],
        "Namsai": [
            "Namsai Circle",
            "Chambang Circle",
            "Meka Circle",
            "Sunpura Circle"
        ],
        "Pakke Kessang": [
            "Bameng Circle",
            "Barkhe Circle",
            "Chayangtajo Circle",
            "Pakke Kessang Hq",
            "Seijosa Circle"
        ],
        "Papum Pare": [
            "Itanagar Hq",
            "Naharlagun",
            "Yupia"
        ],
        "Shi Yomi": [
            "Mechuka Circle",
            "Monigong Circle",
            "Pidi Circle",
            "Tato Circle"
        ],
        "Siang": [
            "Bailo Circle",
            "Kaying Circle",
            "Mebo Circle",
            "Pangin Circle",
            "Siyum Circle"
        ],
        "Tawang": [
            "Jang Circle",
            "Lhou Circle",
            "Lumla Circle",
            "Tawang Hq",
            "Tawang West Circle"
        ],
        "Tirap": [
            "Deomali Circle",
            "Haidong Circle",
            "Kheti Circle",
            "Khonsa Hq",
            "Lalung Circle",
            "Lazu Circle",
            "Namsang Circle",
            "Wakka Circle"
        ],
        "Upper Siang": [
            "Adapani Circle",       
            "Ainang Circle",
            "Geku Circle",
            "Mebo Circle",
            "Morang Circle",
            "Pangin Circle",
            "Tuting Circle"
        ],
        "Upper Subansiri": [
            "Daporijo Hq",
            "Dumporijo Circle",
            "Gensi Circle",
            "Kali Circle",
            "Kaying Circle",
            "Limeking Circle",
            "Nacho Circle",
            "Sarli Circle",
            "Tali Circle"
        ],
        "West Kameng": [
            "Bhalukpong",
            "Bomdila",
            "Dirang",
            "Kalaktang",
            "Kamakshya Hills",
            "Nafra",
            "Pipu",
            "Sawa Circle",
            "Taliha",
            "Tato",
            "Thrizino",
            "Yingkiong"
        ],
        "West Siang": [
            "Aalo Hq",
            "Basar Circle",
            "Bailo Circle", 
            "Chetam Circle",
            "Geku Circle",
            "Kaying Circle",
            "Mebo Circle",
            "Pangin Circle",
            "Siyum Circle"
        ]
    },
   
        "Assam": {
        "Baksa": ["Mushalpur", "Salbari", "Tamulpur"],
        "Barpeta": ["Barpeta", "Bajali"],
        "Bongaigaon": ["Bongaigaon", "Bijni"],
        "Cachar": ["Silchar", "Lakhipur"],
        "Charaideo": ["Sonari"],
        "Chirang": ["Kajalgaon"],
        "Darrang": ["Mangaldai"],
        "Dhemaji": ["Dhemaji", "Jonai"],
        "Dhubri": ["Dhubri", "Bilasipara"],
        "Dibrugarh": ["Dibrugarh"],
        "Dima Hasao": [],  # Subdivisions not listed clearly in source
        "Goalpara": ["Goalpara"],
        "Golaghat": ["Golaghat", "Bokakhat", "Dhansiri"],
        "Hailakandi": ["Hailakandi"],
        "Jorhat": ["Jorhat", "Titabor"],
        "Kamrup Metropolitan": ["Guwahati"],
        "Kamrup (Rural)": ["Amingaon", "Rangia"],
        "Karbi Anglong": ["Diphu", "Hamren", "Bokajan"],
        "Karimganj": ["Karimganj"],
        "Kokrajhar": ["Kokrajhar", "Gossaigaon"],
        "Lakhimpur": ["North Lakhimpur", "Dhakuakhana"],
        "Majuli": [],  # subdivisions info not found
        "Morigaon": ["Morigaon"],
        "Nagaon": ["Nagaon", "Hojai", "Kaliabor"],
        "Nalbari": ["Nalbari"],
        "Sivasagar": ["Sivasagar"],
        "Sonitpur": ["Gohpur", "Biswanath Chariali", "Tezpur"],
        "South Salmara-Mankachar": [],  # info not found
        "Tamulpur": [],  # info not found (Tamulpur is part of Baksa now)
        "Tinsukia": ["Sadiya", "Margherita"],
        "Udalguri": ["Udalguri", "Bhergaon"],
        "West Karbi Anglong": []  # info not found
    },
    "Bihar": {
        "Araria": ["Araria", "Forbesganj"],  # subdivisions
        "Arwal": ["Arwal"],
        "Aurangabad": ["Aurangabad", "Daudnagar"],
        "Banka": ["Banka"],
        "Begusarai": ["Begusarai", "Teghra", "Manjhaul", "Bakhri", "Balia"],
        "Bhagalpur": ["Bhagalpur Sadar", "Kahalgaon", "Naugachhia"],
        "Bhojpur": ["Arrah Sadar", "Jagdishpur", "Piro"],
        "Buxar": ["Buxar"],
        "Darbhanga": ["Darbhanga", "Benipur"],  # Benipur is a subdivision per some sources
        "East Champaran": ["Motihari", "Chakia", "Kesariya", "Raxaul"],  # subdivisions list partial
        "Gaya": ["Gaya Sadar", "Tekari"],
        "Gopalganj": ["Gopalganj", "Hathua"],
        "Jamui": ["Jamui"],
        "Jehanabad": ["Jehanabad"],
        "Khagaria": ["Khagaria"],
        "Kishanganj": ["Kishanganj"],
        "Kaimur": ["Bhabua"],
        "Katihar": ["Katihar"],
        "Lakhisarai": ["Lakhisarai"],
        "Madhepura": ["Madhepura", "Alamnagar"],  # Alamnagar is a subdivision etc.
        "Madhubani": ["Madhubani", "Benipatti", "Jhanjharpur", "Phulparas", "Jainagar"],
        "Munger": ["Munger", "Tarapur"],
        "Muzaffarpur": ["Muzaffarpur East", "Muzaffarpur West", "Haveli Kharagpur", "Taraiya"],
        "Nalanda": ["Bihar Sharif", "Hilsa", "Rajgir"],
        "Nawada": ["Nawada", "Rajauli"],
        "Patna": ["Patna Sadar", "Patna City", "Danapur", "Masaurhi", "Barh", "Paliganj"],
        "Purnia": ["Purnia Sadar", "Banmankhi", "Dhamdaha", "Baisi"],
        "Rohtas": ["Sasaram", "Dehri"],
        "Saharsa": ["Saharsa Sadar", "Simri Bakhtiyarpur"],
        "Samastipur": ["Samastipur", "Dalsinghsarai", "Rosera", "Patori"],
        "Sheikhpura": ["Sheikhpura"],
        "Sheohar": ["Sheohar"],
        "Siwan": ["Siwan Sadar", "Maharajganj"],
        "Saran": ["Chhapra", "Marhaura", "Sonepur"],
        "Sitamarhi": ["Sitamarhi Sadar", "Belsand", "Pupri"],
        "Supaul": ["Supaul", "Birpur", "Nirmali", "Triveniganj"],
        "Vaishali": ["Hajipur", "Mahnar", "Mahua"],
        "West Champaran": ["Bettiah", "Bagaha", "Narkatiaganj"],
    },
"Chandigarh": {
    "Chandigarh": [
        "Central", 
        "East", 
        "South"
    ]
},
"Chattisgarh": {
     "Surguja Division": [
        "Balrampur-Ramanujganj",
        "Jashpur",
        "Koriya",
        "Manendragarh",
        "Surajpur",
        "Surguja"
    ],
    "Bilaspur Division": [
        "Bilaspur",
        "Gaurella-Pendra-Marwahi",
        "Janjgir-Champa",
        "Korba",
        "Mungeli",
        "Raigarh",
        "Sakti",
        "Sarangarh-Bilaigarh"
    ],
    "Durg Division": [
        "Balod",
        "Bemetara",
        "Durg",
        "Kabirdham",
        "Khairagarh-Chhuikhadan-Gandai",
        "Mohla-Manpur-Ambagarh Chowki",
        "Rajnandgaon"
    ],
    "Raipur Division": [
        "Baloda Bazar-Bhatapara",
        "Dhamtari",
        "Gariaband",
        "Mahasamund",
        "Raipur"
    ],
    "Bastar Division": [
        "Bastar",
        "Bijapur",
        "Dantewada",
        "Kanker",
        "Kondagaon",
        "Narayanpur",
        "Sukma"
    ]
    
},
"Dadra and Nagar Haveli and Daman and Diu": {
    "Dadra and Nagar Haveli": ["Silvassa"],
    "Daman": ["Daman"],
    "Diu": ["Diu"]
},
"Delhi": {
    "Central Delhi": ["Darya Ganj", "Karol Bagh", "Paharganj"],
    "East Delhi": ["Preet Vihar", "Mayur Vihar", "Laxmi Nagar"],
    "New Delhi": ["Chanakyapuri", "Connaught Place", "Jama Masjid"],
    "North Delhi": ["Civil Lines", "Model Town", "Sadar Bazar"],
    "North East Delhi": ["Seelampur", "Gokulpuri", "Karawal Nagar"],
    "North West Delhi": ["Rohini", "Pitampura", "Keshav Puram"],
    "Shahdara": ["Dilshad Garden", "Shahdara", "Welcome"],
    "South Delhi": ["Hauz Khas", "Saket", "Mehrauli"],
    "South East Delhi": ["Okhla", "Sarita Vihar", "Badarpur"],
    "South West Delhi": ["Dwarka", "Palam", "Vasant Vihar"],
    "West Delhi": ["Janakpuri", "Rajouri Garden", "Tilak Nagar"]
},
"Goa": {
    "North Goa": ["Panaji", "Mapusa", "Bicholim", "Pernem", "Sattari", "Tiswadi"],
    "South Goa": ["Margao", "Vasco da Gama", "Mormugao", "Quepem", "Salcete", "Sanguem"]
},
"Haryana": {
    "Ambala": ["Ambala", "Naraingarh", "Barara"],
    "Bhiwani": ["Bhiwani", "Loharu", "Tosham"],
    "Charkhi Dadri": ["Charkhi Dadri"],
    "Faridabad": ["Faridabad", "Ballabgarh"],
    "Fatehabad": ["Fatehabad", "Ratia"],
    "Gurgaon": ["Gurgaon", "Pataudi"],
    "Hisar": ["Hisar", "Hansi", "Narnaund"],
    "Jhajjar": ["Jhajjar", "Bahadurgarh"],
    "Jind": ["Jind", "Safidon"],
    "Kaithal": ["Kaithal", "Pundri"],
    "Karnal": ["Karnal", "Assandh"],
    "Kurukshetra": ["Kurukshetra", "Pehowa"],
    "Mahendragarh": ["Narnaul", "Mahendragarh"],
    "Mewat (Nuh)": ["Nuh", "Punahana"],
    "Palwal": ["Palwal", "Hodal"],
    "Panchkula": ["Panchkula", "Pinjore"],
    "Panipat": ["Panipat", "Israna"],
    "Rewari": ["Rewari", "Kosli"],
    "Rohtak": ["Rohtak", "Meham"],
    "Sirsa": ["Sirsa", "Ellenabad"],
    "Sonipat": ["Sonipat", "Ganaur"],
    "Yamunanagar": ["Yamunanagar", "Jagadhri"]
},
"Jammu and Kashmir": {
    "Anantnag": ["Anantnag", "Bijbehara", "Pahalgam"],
    "Bandipora": ["Bandipora", "Sopore"],
    "Baramulla": ["Baramulla", "Tangmarg", "Uri"],
    "Budgam": ["Budgam", "Chadoora"],
    "Doda": ["Doda", "Kishtwar"],
    "Ganderbal": ["Ganderbal", "Kangan"],
    "Jammu": ["Jammu", "Samba", "Kathua"],
    "Kathua": ["Kathua", "Hiranagar"],
    "Kishtwar": ["Kishtwar", "Doda"],
    "Kulgam": ["Kulgam", "Devsar"],
    "Kupwara": ["Kupwara", "Handwara"],
    "Poonch": ["Poonch", "Rajouri"],
    "Pulwama": ["Pulwama", "Tral"],
    "Rajouri": ["Rajouri", "Poonch"],
    "Ramban": ["Ramban", "Banihal"],
    "Reasi": ["Reasi", "Bhimber Gali"],
    "Samba": ["Samba", "Jammu"],
    "Shopian": ["Shopian", "Zainapora"],
    "Srinagar": ["Srinagar", "Budgam"]
},
"Jharkhand": {
    "Bokaro": ["Bokaro Steel City", "Phusro"],
    "Chatra": ["Chatra"],
    "Deoghar": ["Deoghar", "Madhupur"],
    "Dhanbad": ["Dhanbad", "Jharia", "Sindri"],
    "Dumka": ["Dumka", "Rampurhat"],
    "East Singhbhum": ["Jamshedpur", "Ghatshila"],
    "Garhwa": ["Garhwa"],
    "Giridih": ["Giridih", "Bagodar"],
    "Godda": ["Godda"],
    "Gumla": ["Gumla", "Simdega"],
    "Hazaribagh": ["Hazaribagh", "Barhi"],
    "Jamtara": ["Jamtara"],
    "Khunti": ["Khunti"],
    "Koderma": ["Koderma"],
    "Latehar": ["Latehar"],
    "Lohardaga": ["Lohardaga"],
    "Pakur": ["Pakur"],
    "Palamu": ["Medininagar (Daltonganj)", "Chhatarpur"],
    "Ramgarh": ["Ramgarh"],
    "Ranchi": ["Ranchi", "Namkum", "Ormanjhi"],
    "Sahibganj": ["Sahibganj"],
    "Saraikela-Kharsawan": ["Saraikela", "Kharsawan"],
    "Simdega": ["Simdega"]  
},
"Karnataka": {
    "Bagalkot": ["Bagalkot", "Badami", "Hungund"],
    "Bangalore Rural": ["Devanahalli", "Hoskote", "Nelamangala"],
    "Bangalore Urban": ["Bangalore North", "Bangalore South", "Bangalore East", "Bangalore West"],
    "Belagavi": ["Belagavi", "Gokak", "Chikkodi"],
    "Bellary": ["Bellary", "Hospet"],
    "Bidar": ["Bidar", "Humnabad"],
    "Chamarajanagar": ["Chamarajanagar", "Yelandur"],
    "Chikballapur": ["Chikballapur", "Gauribidanur"],
    "Chikkamagaluru": ["Chikkamagaluru", "Mudigere"],
    "Dakshina Kannada": ["Mangaluru", "Puttur", "Sullia"],
    "Davanagere": ["Davanagere", "Harihar"],
    "Dharwad": ["Dharwad", "Hubli-Dharwad"],
    "Gadag": ["Gadag", "Ron"],
    "Hassan": ["Hassan", "Arsikere"],
    "Haveri": ["Haveri", "Byadgi"],
    "Kalaburagi (Gulbarga)": ["Kalaburagi", "Shahabad"],
    "Kodagu": ["Madikeri", "Virajpet"],
    "Kolar": ["Kolar", "Mulbagal"],
    "Koppal": ["Koppal", "Gangavathi"],
    "Mandya": ["Mandya", "Maddur"],
    "Mysuru (Mysore)": ["Mysuru", "Nanjangud"],
    "Raichur": ["Raichur", "Manvi"],
    "Ramanagara": ["Ramanagara", "Kanakapura"],
    "Shivamogga (Shimoga)": ["Shivamogga", "Sagar"],
    "Tumakuru (Tumkur)": ["Tumakuru", "Tiptur"]
},
"Kerala": {
    "Alappuzha": ["Alappuzha", "Chengannur", "Cherthala"],
    "Ernakulam": ["Kochi", "Aluva", "Muvattupuzha"],
    "Idukki": ["Painavu", "Thodupuzha"],
    "Kannur": ["Kannur", "Taliparamba", "Thalassery"],
    "Kasaragod": ["Kasaragod", "Nileshwaram"],
    "Kollam": ["Kollam", "Punalur", "Paravur"],
    "Kottayam": ["Kottayam", "Changanassery", "Vaikom"],
    "Kozhikode": ["Kozhikode", "Vatakara", "Thamarassery"],
    "Malappuram": ["Malappuram", "Perinthalmanna", "Tirur"],
    "Palakkad": ["Palakkad", "Ottapalam", "Chittur"],
    "Pathanamthitta": ["Pathanamthitta", "Adoor", "Thiruvalla"],
    "Thiruvananthapuram": ["Thiruvananthapuram", "Neyyattinkara", "Varkala"],
    "Thrissur": ["Thrissur", "Chalakudy", "Guruvayur"]
},
"Ladakh": {
    "Kargil": ["Kargil", "Drass"],
    "Leh": ["Leh", "Nubra", "Sakti"]
},
"Lakshadweep": {
    "Agatti": ["Agatti"],
    "Amini": ["Amini"],
    "Andrott": ["Andrott"],
    "Kavaratti": ["Kavaratti"],
    "Kadmat": ["Kadmat"],
    "Minicoy": ["Minicoy"]
},
"Madhya Pradesh": {
    "Agar Malwa": ["Agar", "Malhargarh"],
    "Alirajpur": ["Alirajpur", "Jobat"],
    "Anuppur": ["Anuppur", "Pushprajgarh"],
    "Ashoknagar": ["Ashoknagar", "Chanderi"],
    "Balaghat": ["Balaghat", "Waraseoni"],
    "Barwani": ["Barwani", "Sendhwa"],
    "Betul": ["Betul", "Multai"],
    "Bhind": ["Bhind", "Lahar"],
    "Bhopal": ["Bhopal", "Huzur"],
    "Burhanpur": ["Burhanpur", "Khargone"],
    "Chhatarpur": ["Chhatarpur", "Rajnagar"],
    "Chhindwara": ["Chhindwara", "Parasia"],
    "Damoh": ["Damoh", "Hatta"],
    "Datia": ["Datia", "Seondha"],
    "Dewas": ["Dewas", "Sonkatch"],
    "Dhar": ["Dhar", "Manawar"],
    "Dindori": ["Dindori", "Shahpura"],
    "Guna": ["Guna", "Raghogarh"],
    "Gwalior": ["Gwalior", "Morena"],
    "Harda": ["Harda", "Timarni"],
    "Hoshangabad": ["Hoshangabad", "Seoni-Malwa"],
    "Indore": ["Indore", "Mhow"],
    "Jabalpur": ["Jabalpur", "Sihora"],
    "Jhabua": ["Jhabua", "Thandla"],
    "Katni": ["Katni", "Bahoriband"],
    "Khandwa (East Nimar)": ["Khandwa", "Mundi"],
    "Khargone (West Nimar)": ["Khargone", "Barwani"],
    "Mandla": ["Mandla", "Nainpur"],
    "Mandsaur": ["Mandsaur", "Malhargarh"],
    "Morena": ["Morena", "Gwalior"],
    "Narsinghpur": ["Narsinghpur", "Bichhua"],
    "Neemuch": ["Neemuch", "Manasa"],
    "Panna": ["Panna", "Ajaygarh"],
    "Raisen": ["Raisen", "Silwani"],
    "Rajgarh": ["Rajgarh", "Khujner"],
    "Ratlam": ["Ratlam", "Mandsaur"],
    "Rewa": ["Rewa", "Mangawan"],
    "Sagar": ["Sagar", "Khurai"],
    "Satna": ["Satna", "Maihar"],
    "Sehore": ["Sehore", "Ashta"],
    "Seoni": ["Seoni", "Chhindwara"],
    "Shahdol": ["Shahdol", "Anuppur"],
    "Shajapur": ["Shajapur", "Susner"],
    "Sheopur": ["Sheopur", "Vijaypur"],
    "Shivpuri": ["Shivpuri", "Karera"],
    "Sidhi": ["Sidhi", "Singrauli"],
    "Singrauli": ["Singrauli", "Chitrangi"],
},
"Manipur": {
    "Bishnupur": ["Bishnupur", "Nambol"],
    "Chandel": ["Chandel", "Tengnoupal"],
    "Churachandpur": ["Churachandpur", "Sadar Hills"],
    "Imphal East": ["Imphal East", "Porompat"],
    "Imphal West": ["Imphal West", "Lamphelpat"],
    "Jiribam": ["Jiribam"],
    "Kakching": ["Kakching", "Waikhong"],
    "Kamjong": ["Kamjong", "Phungyar"],
    "Kangpokpi": ["Kangpokpi", "Saitu"],
    "Noney": ["Noney", "Longmai"],
    "Pherzawl": ["Pherzawl", "Thanlon"],
    "Senapati": ["Senapati", "Tadubi"],
    "Tamenglong": ["Tamenglong", "Tamei"],
    "Thoubal": ["Thoubal", "Wangkhei"],
    "Ukhrul": ["Ukhrul", "Phungyar"]
},
 "Meghalaya": {
    "East Garo Hills": ["Williamnagar", "Rongram"],
    "East Jaintia Hills": ["Khliehriat", "Saipung"],
    "East Khasi Hills": ["Shillong", "Mawkynrew", "Mawsynram"],
    "North Garo Hills": ["Resubelpara", "Songsak"],
    "Ri Bhoi": ["Nongpoh", "Umiam"],
    "South Garo Hills": ["Baghmara", "Selsella"],
    "South West Garo Hills": ["Ampati", "Dadenggre"],
    "West Garo Hills": ["Tura", "Dalu"],
    "West Jaintia Hills": ["Jowai", "Nartiang"],
    "West Khasi Hills": ["Nongstoin", "Mairang"]
 },
 "Mizoram": {
    "Aizawl": ["Aizawl", "Tlangnuam"],
    "Champhai": ["Champhai", "Khawzawl"],
    "Kolasib": ["Kolasib", "Serchhip"],
    "Lawngtlai": ["Lawngtlai", "Lunglei"],
    "Lunglei": ["Lunglei", "Thorang"],
    "Mamit": ["Mamit", "Dampa"],
    "Saiha": ["Saiha", "Tuipang"],
    "Serchhip": ["Serchhip", "North Vanlaiphai"]
 },
 "Nagaland": {
    "Dimapur": ["Dimapur", "Chumukedima"],
    "Kohima": ["Kohima", "Chiephobozou"],
    "Mokokchung": ["Mokokchung", "Tuli"],
    "Mon": ["Mon", "Phomching"],
    "Peren": ["Peren", "Tening"],
    "Tuensang": ["Tuensang", "Sangphur"],
    "Wokha": ["Wokha", "Atoizu"],
    "Zunheboto": ["Zunheboto", "Satakha"]
 },
"Odisha": {
    "Angul": ["Angul", "Talcher"],
    "Balangir": ["Balangir", "Titlagarh"],
    "Balasore": ["Balasore", "Nilagiri"],
    "Bargarh": ["Bargarh", "Barpali"],
    "Bhadrak": ["Bhadrak", "Dhamnagar"],
    "Boudh": ["Boudh", "Harbhanga"],
    "Cuttack": ["Cuttack", "Niali"],
    "Deogarh": ["Deogarh", "Tileibani"],
    "Dhenkanal": ["Dhenkanal", "Kamakhyanagar"],
    "Gajapati": ["Paralakhemundi", "Rayagada"],
    "Ganjam": ["Bhanjanagar", "Berhampur"],
    "Jagatsinghpur": ["Jagatsinghpur", "Tirtol"],
    "Jajpur": ["Jajpur", "Daspalla"],
    "Jharsuguda": ["Jharsuguda", "Lakhanpur"],
    "Kalahandi": ["Bhawanipatna", "Junagarh"],
    "Kandhamal": ["Phulbani", "Balliguda"],
    "Kendrapara": ["Kendrapara", "Aul"],
    "Kendujhar (Keonjhar)": ["Kendujhar", "Champua"],
    "Khordha": ["Khordha", "Tangi"],
    "Koraput": ["Koraput", "Jeypore"],
    "Malkangiri": ["Malkangiri", "Mathili"],
    "Mayurbhanj": ["Baripada", "Rairangpur"],
    "Nabarangpur": ["Nabarangpur", "Umerkote"],
    "Nuapada": ["Nuapada", "Sinapali"],
    "Puri": ["Puri", "Satyabadi"],
    "Rayagada": ["Rayagada", "Gunupur"],
    "Sambalpur": ["Sambalpur", "Rairakhol"],
    "Subarnapur (Sonepur)": ["Sonepur", "Birmaharajpur"],
    "Sundargarh": ["Sundargarh", "Rourkela"]
},
"Puducherry": {
    "Karaikal": ["Karaikal"],
    "Mahe": ["Mahe"],
    "Puducherry": ["Puducherry", "Ozhukarai", "Ariyankuppam"],
    "Yanam": ["Yanam"]
},
"Punjab": {
    "Amritsar": ["Amritsar", "Ajnala"],
    "Barnala": ["Barnala", "Tapa"],
    "Bathinda": ["Bathinda", "Rampura Phul"],
    "Faridkot": ["Faridkot", "Kotkapura"],
    "Fatehgarh Sahib": ["Fatehgarh Sahib", "Khamano"],
    "Fazilka": ["Fazilka", "Abohar"],
    "Gurdaspur": ["Gurdaspur", "Batala"],
    "Hoshiarpur": ["Hoshiarpur", "Nangal"],
    "Jalandhar": ["Jalandhar", "Nakodar"],
    "Kapurthala": ["Kapurthala", "Phagwara"],
    "Ludhiana": ["Ludhiana", "Sahnewal"],
    "Mansa": ["Mansa", "Budhlada"],
    "Moga": ["Moga", "Bagha Purana"],
    "Muktsar (Sri Muktsar Sahib)": ["Sri Muktsar Sahib", "Malout"],
    "Pathankot": ["Pathankot", "Dera Baba Nanak"],
    "Patiala": ["Patiala", "Rajpura"],
    "Rupnagar (Ropar)": ["Rupnagar", "Nangal"],
    "Sangrur": ["Sangrur", "Sunam"],
    "SAS Nagar (Mohali)": ["Mohali", "Kharar"],
    "Tarn Taran": ["Tarn Taran", "Patti"]
},
"Rajasthan": {
    "Ajmer": ["Ajmer", "Kishangarh"],
    "Alwar": ["Alwar", "Bharatpur"],
    "Banswara": ["Banswara", "Ghatol"],
    "Baran": ["Baran", "Atru"],
    "Barmer": ["Barmer", "Balotra"],
    "Bharatpur": ["Bharatpur", "Deeg"],
    "Bhilwara": ["Bhilwara", "Shahpura"],
    "Bikaner": ["Bikaner", "Lunkaransar"],
    "Bundi": ["Bundi", "Keshoraipatan"],
    "Chittorgarh": ["Chittorgarh", "Kapasan"],
    "Churu": ["Churu", "Taranagar"],
    "Dausa": ["Dausa", "Lalsot"],
    "Dholpur": ["Dholpur", "Rajakhera"],
    "Dungarpur": ["Dungarpur", "Sagwara"],
    "Hanumangarh": ["Hanumangarh", "Nohar"],
    "Jaipur": ["Jaipur", "Sanganer", "Bagru"],
    "Jaisalmer": ["Jaisalmer", "Pokaran"],
    "Jalore": ["Jalore", "Ahore"],
    "Jhalawar": ["Jhalawar", "Kota"],
    "Jhunjhunu": ["Jhunjhunu", "Nawalgarh"],
    "Jodhpur": ["Jodhpur", "Osian"],
    "Karauli": ["Karauli", "Hindaun"],
    "Kota": ["Kota", "Ramganj Mandi"],
    "Nagaur": ["Nagaur", "Merta City"],
    "Pali": ["Pali", "Marwar Junction"],
    "Pratapgarh": ["Pratapgarh", "Chhoti Sadri"],
    "Rajsamand": ["Rajsamand", "Kumbhalgarh"],
    "Sawai Madhopur": ["Sawai Madhopur", "Gangapur City"],
    "Sikar": ["Sikar", "Neem Ka Thana"],
    "Sirohi": ["Sirohi", "Mount Abu"],
    "Sri Ganganagar": ["Sri Ganganagar", "Sadulshahar"],
    "Tonk": ["Tonk", "Deoli"],
    "Udaipur": ["Udaipur", "Kotra"]
},

"Sikkim": {
    "East Sikkim": ["Gangtok", "Ranipool"],
    "North Sikkim": ["Mangan", "Lachen"],
    "South Sikkim": ["Namchi", "Ravangla"],
    "West Sikkim": ["Gyalshing", "Pelling"]
},
"Tamil Nadu": {
    "Ariyalur": ["Ariyalur", "Jayankondam"],
    "Chennai": ["Chennai Central", "Chennai South", "Chennai North"],
    "Coimbatore": ["Coimbatore North", "Coimbatore South"],
    "Cuddalore": ["Cuddalore", "Panruti"],
    "Dharmapuri": ["Dharmapuri", "Harur"],
    "Dindigul": ["Dindigul", "Palani"],
    "Erode": ["Erode", "Bhavani"],
    "Kanchipuram": ["Kanchipuram", "Sriperumbudur"],
    "Kanyakumari": ["Nagercoil", "Kanyakumari"],
    "Karur": ["Karur", "Krishnarayapuram"],
    "Krishnagiri": ["Krishnagiri", "Uthangarai"],
    "Madurai": ["Madurai North", "Madurai South"],
    "Nagapattinam": ["Nagapattinam", "Kilvelur"],
    "Namakkal": ["Namakkal", "Rasipuram"],
    "Perambalur": ["Perambalur", "Veppanthattai"],
    "Pudukkottai": ["Pudukkottai", "Alangudi"],
    "Ramanathapuram": ["Ramanathapuram", "Paramakudi"],
    "Salem": ["Salem North", "Salem South"],
    "Sivaganga": ["Sivaganga", "Tirupathur"],
    "Thanjavur": ["Thanjavur", "Papanasam"],
    "The Nilgiris": ["Udhagamandalam (Ooty)", "Coonoor"],
    "Theni": ["Theni", "Periyakulam"],
    "Thoothukudi (Tuticorin)": ["Thoothukudi", "Vilathikulam"],
    "Tiruchirappalli (Trichy)": ["Tiruchirappalli East", "Tiruchirappalli West"],
    "Tirunelveli": ["Tirunelveli", "Palayamkottai"],
    "Tiruppur": ["Tiruppur North", "Tiruppur South"],
    "Tiruvallur": ["Tiruvallur", "Ponneri"],
    "Tiruvannamalai": ["Tiruvannamalai", "Cheyyar"],
    "Vellore": ["Vellore", "Gudiyatham"]
},
"Telangana": {
    "Adilabad": ["Adilabad", "Nirmal"],
    "Bhadradri Kothagudem": ["Kothagudem", "Bhadrachalam"],
    "Hyderabad": ["Hyderabad", "Secunderabad"],
    "Jagtial": ["Jagtial", "Metpally"],
    "Jangaon": ["Jangaon", "Ghanpur"],
    "Jayashankar Bhupalpally": ["Bhupalpally", "Mulugu"],
    "Jogulamba Gadwal": ["Gadwal", "Alampur"],
    "Kamareddy": ["Kamareddy", "Bodhan"],
    "Karimnagar": ["Karimnagar", "Huzurabad"],
    "Khammam": ["Khammam", "Yellandu"],
    "Komaram Bheem Asifabad": ["Asifabad", "Sirpur"],
    "Mahabubabad": ["Mahabubabad", "Thorrur"],
    "Mahabubnagar": ["Mahabubnagar", "Nagarkurnool"],
    "Mancherial": ["Mancherial", "Bellampalli"],
    "Medak": ["Medak", "Sangareddy"],
    "Medchal-Malkajgiri": ["Malkajgiri", "Quthbullapur"],
    "Mulugu": ["Mulugu", "Chintoor"],
    "Nagarkurnool": ["Nagarkurnool", "Achampet"],
    "Nalgonda": ["Nalgonda", "Miryalaguda"],
    "Narayanpet": ["Narayanpet", "Kosgi"],
    "Nirmal": ["Nirmal", "Adilabad"],
    "Nizamabad": ["Nizamabad", "Bodhan"],
    "Peddapalli": ["Peddapalli", "Ramagundam"],
    "Rajanna Sircilla": ["Sircilla", "Vemulawada"],
    "Rangareddy": ["Shamshabad", "Chevella"],
    "Sangareddy": ["Sangareddy", "Medak"],
    "Siddipet": ["Siddipet", "Gajwel"],
    "Suryapet": ["Suryapet", "Kodad"],
    "Vikarabad": ["Vikarabad", "Pargi"],
    "Wanaparthy": ["Wanaparthy", "Pebbair"],
    "Warangal Rural": ["Warangal", "Narsampet"],
    "Warangal Urban": ["Warangal", "Hanamkonda"]
},
"Tripura": {
    "Dhalai": ["Ambassa", "Kamalpur"],
    "Gomati": ["Udaipur", "Amarpur"],
    "Khowai": ["Khowai", "Teliamura"],
    "North Tripura": ["Dharmanagar", "Kanchanpur"],
    "Sepahijala": ["Sonamura", "Nalchar"],
    "South Tripura": ["Belonia", "Sabroom"],
    "Unakoti": ["Kailashahar", "Kumarghat"]
},
"Uttar Pradesh": {
    "Agra": ["Agra", "Fatehabad"],
    "Aligarh": ["Aligarh", "Khair"],
    "Allahabad (Prayagraj)": ["Prayagraj", "Phulpur"],
    "Ambedkar Nagar": ["Akbarpur", "Tanda"],
    "Amethi": ["Amethi", "Gauriganj"],
    "Amroha": ["Amroha", "Dhanaura"],
    "Auraiya": ["Auraiya", "Ajitmal"],
    "Azamgarh": ["Azamgarh", "Mau"],
    "Baghpat": ["Baghpat", "Baraut"],
    "Bahraich": ["Bahraich", "Nanpara"],
    "Ballia": ["Ballia", "Bairia"],
    "Balrampur": ["Balrampur", "Tulsipur"],
    "Banda": ["Banda", "Atarra"],
    "Barabanki": ["Barabanki", "Zaidpur"],
    "Bareilly": ["Bareilly", "Aonla"],
    "Basti": ["Basti", "Dhanghata"],
    "Bijnor": ["Bijnor", "Najibabad"],
    "Budaun": ["Budaun", "Dataganj"],
    "Bulandshahr": ["Bulandshahr", "Sikandrabad"],
    "Chandauli": ["Chandauli", "Mughal Sarai"],
    "Chitrakoot": ["Chitrakoot", "Manikpur"],
    "Deoria": ["Deoria", "Salempur"],
    "Etah": ["Etah", "Kasganj"],
    "Etawah": ["Etawah", "Saifai"],
    "Farrukhabad": ["Farrukhabad", "Kaimganj"],
    "Fatehpur": ["Fatehpur", "Bindki"],
    "Firozabad": ["Firozabad", "Shikohabad"],
    "Gautam Buddha Nagar": ["Noida", "Greater Noida"],
    "Ghaziabad": ["Ghaziabad", "Loni"],
    "Ghazipur": ["Ghazipur", "Zamania"],
    "Gonda": ["Gonda", "Colonelganj"],
    "Gorakhpur": ["Gorakhpur", "Sadar"],
    "Hamirpur": ["Hamirpur", "Maudaha"],
    "Hapur": ["Hapur", "Garhmukteshwar"],
    "Hardoi": ["Hardoi", "Sandila"],
    "Hathras": ["Hathras", "Sadabad"],
    "Jalaun": ["Orai", "Kalpi"],
    "Jaunpur": ["Jaunpur", "Shahganj"],
    "Jhansi": ["Jhansi", "Mauranipur"],
    "Kannauj": ["Kannauj", "Tirwa"],
    "Kanpur Dehat": ["Akbarpur", "Bhognipur"],
    "Kanpur Nagar": ["Kanpur", "Kalyanpur"],
    "Kasganj": ["Kasganj", "Patiali"],
    "Kaushambi": ["Manjhanpur", "Chail"],
    "Kushinagar": ["Kushinagar", "Padrauna"],
    "Lakhimpur Kheri": ["Lakhimpur", "Palia"],
    "Lalitpur": ["Lalitpur", "Talbehat"],
    "Lucknow": ["Lucknow", "Malihabad"],
    "Maharajganj": ["Maharajganj", "Paniyara"],
    "Mahoba": ["Mahoba", "Charkhari"],
    "Mainpuri": ["Mainpuri", "Kishni"],
    "Mathura": ["Mathura", "Chhata"],
    "Mau": ["Mau", "Ghosi"],
    "Meerut": ["Meerut", "Sardhana"],
    "Mirzapur": ["Mirzapur", "Chunar"],
    "Moradabad": ["Moradabad", "Thakurdwara"],
    "Muzaffarnagar": ["Muzaffarnagar", "Khatauli"],
    "Pilibhit": ["Pilibhit", "Barkhera"],
    "Pratapgarh": ["Pratapgarh", "Kunda"],
    "Rae Bareli": ["Rae Bareli", "Salon"],
    "Rampur": ["Rampur", "Bilaspur"],
    "Saharanpur": ["Saharanpur", "Deoband"],
    "Sambhal": ["Sambhal", "Chandausi"],
    "Sant Kabir Nagar": ["Khalilabad", "Mehdawal"],
    "Shahjahanpur": ["Shahjahanpur", "Tilhar"],
    "Shamli": ["Shamli", "Thana Bhawan"],
    "Shravasti": ["Bhinga", "Tulsipur"],
    "Siddharthnagar": ["Naugarh", "Bansi"],
    "Sitapur": ["Sitapur", "Misrikh"],
    "Sonbhadra": ["Sonbhadra", "Robertsganj"],
    "Sultanpur": ["Sultanpur", "Kadipur"],
    "Unnao": ["Unnao", "Safipur"],
    "Varanasi": ["Varanasi", "Chiraigaon"]
},
"Uttarakhand": {
    "Almora": ["Almora", "Ranikhet"],
    "Bageshwar": ["Bageshwar", "Kanda"],
    "Chamoli": ["Chamoli", "Joshimath"],
    "Champawat": ["Champawat", "Pati"],
    "Dehradun": ["Dehradun", "Rishikesh"],
    "Haridwar": ["Haridwar", "Roorkee"],
    "Nainital": ["Nainital", "Haldwani"],
    "Pauri Garhwal": ["Pauri", "Kotdwar"],
    "Pithoragarh": ["Pithoragarh", "Dharchula"],
    "Rudraprayag": ["Rudraprayag", "Karnaprayag"],
    "Tehri Garhwal": ["Tehri", "New Tehri"],
    "Udham Singh Nagar": ["Rudrapur", "Kichha"]
},
"West Bengal": {
    "Alipurduar": ["Alipurduar", "Kalchini"],
    "Bankura": ["Bankura", "Khatra"],
    "Birbhum": ["Suri", "Rampurhat"],
    "Cooch Behar": ["Cooch Behar", "Dinhata"],
    "Dakshin Dinajpur": ["Balurghat", "Gangarampur"],
    "Darjeeling": ["Darjeeling", "Siliguri"],
    "Hooghly": ["Chinsurah", "Serampore"],
    "Howrah": ["Howrah", "Uluberia"],
    "Jalpaiguri": ["Jalpaiguri", "Malbazar"],
    "Jhargram": ["Jhargram", "Gopiballavpur"],
    "Kalimpong": ["Kalimpong"],
    "Kolkata": ["Kolkata"],
    "Malda": ["Malda", "English Bazar"],
    "Murshidabad": ["Berhampore", "Domkal"],
    "Nadia": ["Krishnanagar", "Ranaghat"],
    "North 24 Parganas": ["Barasat", "Bangaon"],
    "Paschim Bardhaman": ["Asansol", "Durgapur"],
    "Paschim Medinipur": ["Midnapore", "Kharagpur"],
    "Purba Bardhaman": ["Bardhaman", "Katwa"],
    "Purba Medinipur": ["Tamluk", "Haldia"],
    "Purulia": ["Purulia", "Raghunathpur"],
    "South 24 Parganas": ["Alipore Sadar", "Diamond Harbour"],
    "Uttar Dinajpur": ["Raiganj", "Islampur"]
}
}